name: Build document

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install dependencies
      run:  |
        sudo apt update
        sudo apt install -y graphviz
        pip install -U tox
    - name: Run Tox
      run:  tox -e docs
