name: Lint source code

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: [docslint, flake8, isort, mypy, twine]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install dependencies
      run:  pip install -U tox
    - name: Run Tox
      run:  tox -e ${{ matrix.tool }}
