name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        name: [py36, py37, py38, py39, py310]
        include:
        - name: py36
          python: 3.6
          docutils: du14
        - name: py37
          python: 3.7
          docutils: du15
        - name: py38
          python: 3.8
          docutils: du16
        - name: py39
          python: 3.9
          docutils: du17
          coverage: "--cov ./ --cov-append --cov-config setup.cfg"
        - name: py310
          python: "3.10"
          docutils: du17
        - name: py311-dev
          python: 3.11-dev
          docutils: py311
    env:
      PYTEST_ADDOPTS: ${{ matrix.coverage }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      if: "!endsWith(matrix.python, '-dev')"
      with:
        python-version: ${{ matrix.python }}
    - name: Set up Python ${{ matrix.python }} (deadsnakes)
      uses: deadsnakes/action@v2.0.1
      if: endsWith(matrix.python, '-dev')
      with:
        python-version: ${{ matrix.python }}
    - name: Check Python version
      run: python --version
    - name: Install graphviz
      run: sudo apt-get install graphviz
    - name: Install dependencies
      run: pip install -U tox codecov
    - name: Install the latest py package (for py3.11-dev)
      run: pip install -U git+https://github.com/pytest-dev/py
      if: ${{ matrix.python == '3.11-dev' }}
    - name: Run Tox
      run: tox -e ${{ matrix.docutils }} -- -vv
    - name: codecov
      uses: codecov/codecov-action@v1
      if: matrix.coverage

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run:  pip install -U tox
    - name: Run Tox
      run:  tox -e py -- -vv
